"""
ODE / SDE sampling for the flow-based backbone decoder  (Section 3.2, Eq. 6).

During inference, backbone coordinates are generated by integrating either:

  ODE: dx_t = v_θ(x_t, t) dt
  SDE: dx_t = v_θ(x_t, t) dt + g(t) s_θ(x_t, t) dt + √(2g(t)γ) dW_t

where the score function s_θ(x_t, t) = (t·v_θ − x_t) / (1−t).

Key insight (Section 4.3 / Table 2):
  Use SDE at coarse scales (global topology needs stochasticity) and
  ODE at fine scales (local refinement is efficient with just 2 steps).
  This yields 2.5–4.7× inference speedup with no quality degradation.

Default γ = 0.30 (low temperature → higher designability, lower diversity).
"""

from typing import Callable, Optional, Tuple
import torch


# ---------------------------------------------------------------------------
# Score function from flow velocity
# ---------------------------------------------------------------------------

def score_from_velocity(
    x_t:      torch.Tensor,
    v_theta:  torch.Tensor,
    t:        torch.Tensor,
    eps:      float = 1e-5,
) -> torch.Tensor:
    """
    s_θ(x_t, t) = (t · v_θ − x_t) / (1 − t)    (from paper Eq. 6)

    Args:
        x_t:     (B, S, 3) noisy coords at time t
        v_theta: (B, S, 3) velocity predicted by decoder
        t:       (B,) time values in [0, 1]
    Returns:
        (B, S, 3) score estimate
    """
    t_bc = t.view(-1, 1, 1)                          # broadcast over S, 3
    return (t_bc * v_theta - x_t) / (1.0 - t_bc + eps)


# ---------------------------------------------------------------------------
# ODE sampler (deterministic)
# ---------------------------------------------------------------------------

@torch.no_grad()
def ode_sample(
    velocity_fn: Callable,
    x_init: torch.Tensor,
    n_steps: int,
    t_start: float = 1.0,
    t_end: float = 0.0,
    use_self_conditioning: bool = True,
) -> torch.Tensor:
    """
    Euler integration of the ODE  dx_t = v_θ(x_t, t) dt.
    Integrates from noise (t=1) to data (t=0).

    Args:
        velocity_fn:           callable(x_t, t_tensor, self_cond) → velocity (B, S, 3)
        x_init:                (B, S, 3) initial noise
        n_steps:               number of Euler steps
        t_start / t_end:       integration interval
        use_self_conditioning: feed previous x̂ as self-conditioning

    Returns:
        (B, S, 3) generated backbone
    """
    x = x_init.clone()
    B = x.shape[0]
    device = x.device
    dt = (t_end - t_start) / n_steps

    self_cond: Optional[torch.Tensor] = None

    ts = torch.linspace(t_start, t_end - abs(dt), n_steps, device=device)

    for t_val in ts:
        t = torch.full((B,), t_val, device=device, dtype=x.dtype)
        v = velocity_fn(x, t, self_cond)

        if use_self_conditioning:
            self_cond = x + (1.0 - t_val) * v  # x̂ = x_t + (1-t)·v

        x = x + dt * v

    return x


# ---------------------------------------------------------------------------
# SDE sampler (stochastic)
# ---------------------------------------------------------------------------

@torch.no_grad()
def sde_sample(
    velocity_fn: Callable,
    x_init: torch.Tensor,
    n_steps: int,
    gamma: float = 0.30,
    t_start: float = 1.0,
    t_end: float = 0.0,
    g_scale: float = 1.0,
    use_self_conditioning: bool = True,
) -> torch.Tensor:
    """
    Euler–Maruyama integration of the SDE (Eq. 6):
        dx_t = v_θ dt + g(t) s_θ dt + √(2 g(t) γ) dW_t

    where g(t) = g_scale (constant in this implementation).

    Args:
        velocity_fn:           callable(x_t, t_tensor, self_cond) → velocity
        x_init:                (B, S, 3) initial noise
        n_steps:               integration steps
        gamma:                 noise scaling parameter (default 0.30 per paper)
        t_start / t_end:       integration interval [1 → 0]
        g_scale:               constant diffusion coefficient g(t)
        use_self_conditioning: feed previous x̂ as self-conditioning

    Returns:
        (B, S, 3) generated backbone
    """
    x = x_init.clone()
    B, S, _ = x.shape
    device   = x.device
    dt = (t_end - t_start) / n_steps          # negative (integrating backwards)
    abs_dt = abs(dt)

    self_cond: Optional[torch.Tensor] = None

    ts = torch.linspace(t_start, t_end - abs(dt), n_steps, device=device)

    for t_val in ts:
        t = torch.full((B,), t_val, device=device, dtype=x.dtype)
        v = velocity_fn(x, t, self_cond)
        s = score_from_velocity(x, v, t)

        drift = v + g_scale * s
        noise_scale = (2.0 * g_scale * gamma) ** 0.5
        dW = torch.randn_like(x) * (abs_dt ** 0.5)

        x = x + dt * drift + noise_scale * dW

        if use_self_conditioning:
            self_cond = x + (1.0 - t_val) * v

    return x


# ---------------------------------------------------------------------------
# Multi-scale orchestrated sampler (Table 2 strategy)
# ---------------------------------------------------------------------------

@torch.no_grad()
def multiscale_sample(
    velocity_fns: list,
    scale_sizes: list,
    batch_size: int,
    device: torch.device,
    sampling_modes: Optional[list] = None,
    n_steps_per_scale: Optional[list] = None,
    gamma: float = 0.30,
    use_self_conditioning: bool = True,
    dtype: torch.dtype = torch.float32,
) -> Tuple[torch.Tensor, list]:
    """
    Autoregressive multi-scale sampling with per-scale SDE/ODE selection.

    This is the key inference loop for PAR (Section 3.2, inference paragraph).
    Achieves 2.5× speedup via SDE at scale 1, ODE at scales 2+ (Table 2).

    Args:
        velocity_fns:         list of n callables, one per scale.
                              Each: fn(x_t, t, self_cond) → velocity (B, S_i, 3)
        scale_sizes:          list of n ints, size of each scale
        batch_size:           B
        device:               torch device
        sampling_modes:       list of n strings: "sde" or "ode" per scale
                              Default: ["sde", "ode", "ode", ...]  (best from Table 2)
        n_steps_per_scale:    list of n ints (default: [400, 2, 2, ...])
        gamma:                SDE noise parameter
        use_self_conditioning:use self-conditioning during decoding
        dtype:                data type

    Returns:
        (B, L, 3) final backbone  (scale n output)
        list of all intermediate scale outputs
    """
    n = len(scale_sizes)

    if sampling_modes is None:
        # Best configuration from Table 2: SDE first, ODE rest
        sampling_modes = ["sde"] + ["ode"] * (n - 1)

    if n_steps_per_scale is None:
        # 400 steps for SDE, 2 for ODE (as in Table 2 S/O/O 400/2/2 row)
        n_steps_per_scale = [
            400 if m == "sde" else 2
            for m in sampling_modes
        ]

    intermediates = []
    x_prev = None  # will be generated at each scale and passed to the next

    for i in range(n):
        S_i    = scale_sizes[i]
        mode   = sampling_modes[i]
        steps  = n_steps_per_scale[i]
        vfn    = velocity_fns[i]

        # Sample initial noise for this scale
        x_noise = torch.randn(batch_size, S_i, 3, device=device, dtype=dtype)

        if mode == "sde":
            x_i = sde_sample(
                vfn, x_noise, steps, gamma=gamma,
                use_self_conditioning=use_self_conditioning,
            )
        elif mode == "ode":
            x_i = ode_sample(
                vfn, x_noise, steps,
                use_self_conditioning=use_self_conditioning,
            )
        else:
            raise ValueError(f"Unknown sampling mode: {mode}")

        intermediates.append(x_i)
        x_prev = x_i

    return intermediates[-1], intermediates
